version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 21
    commands:
      - npm ci

  build:
    commands:
      - npm run build
      - npm run export

artifacts:
  base-directory: out
  files:
    - '**/*'

cache:
  paths:
    - 'node_modules/**/*'